<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE crypto
[
<!ELEMENT crytoname (title)>
<!ELEMENT title (name,price,marketcap)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT marketcap (#PCDATA)>
<!ATTLIST title id ID #REQUIRED>
]>
<crytoname>
<title id="1">
<name>Bitcoin BTC</name>
<price>$39,885.15</price>
<marketcap>$738,433,904,476</marketcap>
</title>
<title  pid="2">
<name>Ethereum ETH</name>
    <price>$2,684.42</price>
    <marketcap>$305,748,011,246</marketcap>
</title>
<title pid="3">
<name>Tether USDT</name>
    <price>$1.00</price>
    <marketcap>$58,627,152,321</marketcap>

</title>
<title pid="4">
<name>Binance Coin BNB</name>
    <price>$377.91</price>
    <marketcap>$57,818,865,221</marketcap>

</title>
</crytoname>
